name: Build and Push to ghcr.io

on:
  workflow_dispatch:
    inputs:
     image_tag:
        description: 'Official image tag to use'
        required: true
        default: 'latest'
        type: string

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: sing-box-routeros

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        id: docker_build_candidate
        uses: docker/build-push-action@v6.1.0
        with:
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          file: Dockerfile
          push: true
          tags: ghcr.io/seemsfishy/${{ env.IMAGE_NAME }}:${{ inputs.image_tag }}
          builder: ${{ steps.buildx.outputs.name }}
